# Generated by Django 5.0.4 on 2024-04-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
