# Generated by Django 5.0.4 on 2024-04-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_cake_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
