# Generated by Django 5.0.4 on 2024-04-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_cake_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='cake',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
