# Generated by Django 5.0.4 on 2024-04-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_remove_cake_ingredients_cake_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='baked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
