# Generated by Django 5.0.4 on 2024-04-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_cake_baked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image_url',
            field=models.URLField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='in gr'),
        ),
    ]
