# Generated by Django 5.0.4 on 2024-04-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_cake_image_url_alter_cake_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='description',
            new_name='ingredients',
        ),
    ]
