# Generated by Django 5.0.4 on 2024-04-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0008_rename_description_cake_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
